#!/bin/bash
echo 0 > /sys/fs/selinux/enforce

# mount shared directories
mkdir -p /common
mount -t nfs 10.64.28.50:/dataNfs /common

# install and configure HTCondor
cd /etc/yum.repos.d
wget http://90.147.77.142/repo/htcondor/repo.d/htcondor-stable-rhel7.repo
yum install -y condor-all-8.6.9

HOSTIP=$(hostname -I | awk '{print $1}')
CUID=$(id condor | awk '{print $1}'| cut -d'=' -f2|cut -d'(' -f1)
CGID=$(id condor | awk '{print $2}'| cut -d'=' -f2|cut -d'(' -f1)
#
cat << EOF > /etc/condor/condor_config.local
DAEMON_LIST = MASTER, STARTD
CONDOR_HOST = %ipv4%
CONDOR_ADMIN = root@%ipv4%

# Preserve UID of submitting user
UID_DOMAIN = *
TRUST_UID_DOMAIN = True
SOFT_UID_DOMAIN = True

CONDOR_IDS = $CUID.$CGID
QUEUE_SUPER_USERS = root, condor
HIGHPORT = 42000
LOWPORT = 41000
NETWORK_INTERFACE = $HOSTIP
NO_DNS = True
DEFAULT_DOMAIN_NAME = INFN-PD
EOF

cat << EOF > /etc/condor/config.d/centos7
###################
# Centos7 Cluster #
###################
SEC_DAEMON_AUTHENTICATION = required
SEC_DAEMON_INTEGRITY = required
SEC_DAEMON_AUTHENTICATION_METHODS = password
SEC_CLIENT_AUTHENTICATION_METHODS = password,fs,gsi,kerberos
SEC_PASSWORD_FILE = /etc/condor/condor_credential
SEC_ENABLE_MATCH_PASSWORD_AUTHENTICATION = True

ALLOW_DAEMON = condor_pool@*, submit-side@matchsession
COLLECTOR_NAME = CernVM cluster at \$(CONDOR_HOST)
NEGOTIATOR_INTERVAL = 20
START = TRUE
SUSPEND = FALSE
PREEMPT = FALSE
KILL = FALSE
TRUST_UID_DOMAIN = TRUE
UPDATE_COLLECTOR_WITH_TCP = True
COLLECTOR_SOCKET_CACHE_SIZE = 1000
CONDOR_DEVELOPERS_COLLECTOR = NONE
EOF

/usr/sbin/condor_store_cred -p 12345 add -f /etc/condor/condor_credential
systemctl start condor
systemctl enable condor

# configure docker
yum install -y docker-io
groupadd docker
usermod -aG docker condor
cat << EOF > /etc/docker/daemon.json
{
	"insecure-registries" : [ "10.64.28.50:5000" ]
}
EOF
systemctl start docker
systemctl enable docker
condor_reconfig
